# Generated by Django 5.1.5 on 2025-02-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genotype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_records', models.FileField(blank=True, null=True, upload_to='MedRecords/media/PatientReports')),
            ],
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('allergies', models.TextField()),
                ('address', models.TextField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('condition', models.TextField()),
                ('hospital', models.CharField(max_length=100)),
                ('emg_name', models.CharField(max_length=100)),
                ('emg_relationship', models.CharField(max_length=100)),
                ('emg_phone_no', models.CharField(max_length=100)),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.bloodgroup')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.gender')),
                ('genotype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.genotype')),
                ('pdf_records', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_pdf_records', to='records.medicalrecords')),
                ('patient_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.patienttype')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_patient', to='records.patient'),
        ),
    ]
